# Generated by Django 5.2 on 2025-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0015_alter_reddit_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegram",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
