# Generated by Django 5.2 on 2025-12-14 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0016_telegram_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("social_post", "Social Post"),
                            ("email", "Email"),
                            ("product_description", "Product Description"),
                            ("blog", "Blog Post"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("topic", models.TextField()),
                ("audience", models.TextField()),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("casual", "Casual"),
                            ("persuasive", "Persuasive"),
                            ("informative", "Informative"),
                            ("humorous", "Humorous"),
                            ("formal", "Formal"),
                        ],
                        max_length=50,
                    ),
                ),
                ("style", models.TextField(blank=True, null=True)),
                (
                    "keywords",
                    models.TextField(
                        blank=True, help_text="Comma-separated keywords", null=True
                    ),
                ),
                (
                    "length",
                    models.CharField(
                        help_text="e.g., 500 words, 280 characters", max_length=100
                    ),
                ),
                (
                    "format",
                    models.TextField(
                        blank=True,
                        help_text="e.g., bullet points, headings, Q&A",
                        null=True,
                    ),
                ),
                (
                    "objective",
                    models.TextField(help_text="What should this content achieve?"),
                ),
                ("generated_content", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
